"""
backend/schemas.py
------------------
Pydantic schemas for data validation and serialization/deserialization.
Includes request/response schemas for Users, Notes, and Study Assistant features.
"""

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, EmailStr


# =====================================================================
# User & Authentication Schemas
# =====================================================================

class UserCreate(BaseModel):
    """Schema for user registration and login requests."""
    email: EmailStr
    password: str


class UserResponse(BaseModel):
    """Schema returned after user registration or querying user profile."""
    id: int
    email: EmailStr
    created_at: datetime

    class Config:
        # Allows Pydantic to read data directly from SQLAlchemy ORM models
        from_attributes = True


class Token(BaseModel):
    """Schema for JWT token response."""
    access_token: str
    token_type: str = "bearer"


class TokenData(BaseModel):
    """Schema for decoded JWT token payload."""
    email: Optional[str] = None


# =====================================================================
# Note Schemas
# =====================================================================

class NoteCreate(BaseModel):
    """Schema for creating/saving a new note in the database."""
    title: str
    filename: str
    summary: Optional[str] = None
    key_points: Optional[str] = None
    notes_content: Optional[str] = None


class NoteResponse(BaseModel):
    """Schema returned when retrieving saved notes."""
    id: int
    user_id: int
    title: str
    filename: str
    summary: Optional[str] = None
    key_points: Optional[str] = None
    notes_content: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True


# =====================================================================
# Study Assistant (AI / RAG) Schemas
# =====================================================================

class AskQuestionRequest(BaseModel):
    """Schema for asking questions against an uploaded document."""
    question: str
    session_id: Optional[str] = None


class AskQuestionResponse(BaseModel):
    """Schema for the QA answer generated with retrieved PDF context."""
    answer: str
    sources: Optional[List[str]] = []


class GenerateNotesResponse(BaseModel):
    """Schema for structured notes, summary, and bullet points generated by Gemini."""
    notes: str
    summary: str
    key_points: List[str]


class QuizQuestion(BaseModel):
    """Schema for a single multiple-choice question."""
    question: str
    options: List[str]
    correct_answer: str
    explanation: Optional[str] = None


class QuizResponse(BaseModel):
    """Schema for a collection of generated quiz questions."""
    quiz: List[QuizQuestion]


    